baseURL: "https://tedb.dev"
title: "tedb.dev"

menu:
  main:
    - name: "Projects"
      url: "/projects"
    # - name: "Blog"
    #   url: "/blog"

  social:
    - name: "Github"
      url: "https://www.github.com/tedbennett"
      pre: "<i class='fab fa-github'></i>"
    - name: "Email"
      url: "mailto:ted_bennett@icloud.com"
      pre: "<i class='far fa-envelope'></i>"

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokailight
    tabWidth: 4
