baseURL: "https://tedb.dev"
title: "tedb.dev"
paginate: 5

menu:
  main:
    - name: "Projects"
      url: "/projects"
    - name: "Blog"
      url: "/blog"
  
  social:
    - name: "Github"
      url: "https://www.github.com/tedbennett"
      pre: "<i class='fab fa-github'></i>"
    - name: "Email"
      url: "mailto:ted_bennett@icloud.com"
      pre: "<i class='far fa-envelope'></i>"

