baseURL: "https://tedb.dev"
title: "tedb.dev"
paginate: 5
# theme: tedb-dev

menu:
  main:
    - name: "Projects"
      url: "/projects"
    - name: "Blog"
      url: "/blog"
  
  social:
    - name: "Github"
      url: "https://www.github.com/tedbennett"
      pre: "<i class='fab fa-github'></i>"
